// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';

export function Countries():Promise<Array<search.Country>>;

export function GetGeo():Promise<search.Country>;

export function NewIdentity():Promise<string>;

export function ProxyAddr():Promise<string>;

export function Search(arg1:string):Promise<search.Results>;

export function SearchDark(arg1:string):Promise<search.Results>;

export function SearchWeb(arg1:string):Promise<search.Results>;

export function SessionHash():Promise<string>;

export function SetCountry(arg1:string):Promise<search.Country>;

export function SetMode(arg1:string):Promise<string>;

export function TorStatus():Promise<boolean>;

export function VerifyIntegrity(arg1:string):Promise<string>;
