// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Countries() {
  return window['go']['main']['App']['Countries']();
}

export function GetGeo() {
  return window['go']['main']['App']['GetGeo']();
}

export function NewIdentity() {
  return window['go']['main']['App']['NewIdentity']();
}

export function ProxyAddr() {
  return window['go']['main']['App']['ProxyAddr']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchDark(arg1) {
  return window['go']['main']['App']['SearchDark'](arg1);
}

export function SearchMore(arg1) {
  return window['go']['main']['App']['SearchMore'](arg1);
}

export function SearchWeb(arg1) {
  return window['go']['main']['App']['SearchWeb'](arg1);
}

export function SessionHash() {
  return window['go']['main']['App']['SessionHash']();
}

export function SetCountry(arg1) {
  return window['go']['main']['App']['SetCountry'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function TorStatus() {
  return window['go']['main']['App']['TorStatus']();
}

export function VerifyIntegrity(arg1) {
  return window['go']['main']['App']['VerifyIntegrity'](arg1);
}
